### ISSUE TITLE
update / publish helm chart to artifacthub.io or any other public helm chart repository

### ISSUE THREAD

**Issue by tprakash17** [fjogeleit/trivy-operator-polr-adapter#102]
currently README has no instructions regarding helm chart installation. I see two months back only helm chart has been added into folder but hasn't been published yet. 

We are currently thinking adopting this to complete our internal k8s security to make sure everything under one umbrella. we already use Kyverno and policy-reports.

**Comment by tprakash17** [comment]
@fjogeleit

**Comment by fjogeleit** [comment]
Hey, thanks for your request.

The README has instructions about adding the Helm Chart from Github pages, but I can also will have a look on adding it to artifacthub.

**Comment by tprakash17** [comment]
@fjogeleit thanks for the prompt reply. I have also watched one of your talk where your team spoke about `falco-adapter` and `trivy-adapter` listed [here](here)

little confuse with trivy-adapter vs `trivy-operator-polr-adapter` ? aren't they same

**Comment by fjogeleit** [comment]
The Trivy Adapter does not translate the different trivy Reports to PolicyReports. It is a CLI to start a scan of existing workloads and creates a PolicyReport out of them. So its an autonomous for local or workflow usage.

Trivy Operator Polr Adapter is related / has a dependency to the Trivy Operator CRDs. It only watches for those CRDs and translates them into (Cluster)PolicyReports, the actual work is done by the Operator.

**Comment by fjogeleit** [comment]
Added to artifact hub: https://artifacthub.io/packages/search?repo=trivy-operator-polr-adapter

Will also get the verified badge soon

**Comment by tprakash17** [comment]
Thank you @fjogeleit

**Comment by tprakash17** [comment]
@fjogeleit https://artifacthub.io/packages/helm/trivy-operator-polr-adapter/trivy-operator-polr-adapter doesn't include a README there. maybe something for later.

**Comment by fjogeleit** [comment]
Will have a look, thanks
