### ISSUE TITLE
Trivy ExposedSecrets etc. not visable in policy reporter

### ISSUE THREAD

**Issue by dekstiertje** [fjogeleit/trivy-operator-polr-adapter#104]
I installed the trivy-adapter but first without additional flags. Later i wanted to see all the report in the policy reporter but if i do: 
``` helm upgrade trivy-operator-polr-adapter trivy-operator-polr-adapter/trivy-operator-polr-adapter -n trivy-adapter --set adapters.vulnerabilityReports.enabled=true,adapters.configAuditReports.enabled=true,adapters.rbacAssessmentReports.enabled=true,adapters.exposedSecretReports.enabled=true,adapters.complianceReports.enabled=true,adapters.infraAssessmentReports.enabled=true,adapters.clusterInfraAssessmentReports.enabled=true,adapters.cisKubeBenchReports.enabled=true ``` . I dont  see the the report in the UI: 
![image](https://github.com/fjogeleit/trivy-operator-polr-adapter/assets/57712393/4d199d59-7bc1-4fbe-8296-a872675c8d8c)

**Comment by fjogeleit** [comment]
Hey, did you check if it created PolicyReports for exposed secret? If you enable it but there is no actual report it will not show up in the UI.

So can you check if you have ExposedSecret reports from the Trivy Operator and the related PolicyReport translations?

**Comment by dekstiertje** [comment]
if i do: kubectl get exposedsecretreports --all-namespaces, i see all the reports.

**Comment by fjogeleit** [comment]
Okay, are you sure that the `--set` argument work this way you used it? I only now the syntax like this: `--set adapters.vulnerabilityReports.enabled=true --set adapters.configAuditReports.enabled=true --set adapters.rbacAssessmentReports.enabled=true ` etc.

**Comment by dekstiertje** [comment]
i did it again but with all --set instead of , and if i do helm get values i see: 
![image](https://github.com/fjogeleit/trivy-operator-polr-adapter/assets/57712393/45688ddc-cfa8-42cd-bc92-61053fcc0e37)

**Comment by fjogeleit** [comment]
Okay, did you check the logs of the adapter? It should log whats enabled and if there are issues while translating the reports.

**Comment by dekstiertje** [comment]
it is fixed now, thanks! :) 
I set CISbench also true but that was not possible for my version, so the adapter was in crashloopbackoff

**Comment by fjogeleit** [comment]
ah okay. Yeah this one is only for very early versions. Nice that its working now.
