### ISSUE TITLE
Thanks for that initiative :)

### ISSUE THREAD

**Issue by sherifkayad** [fjogeleit/trivy-operator-polr-adapter#46]
Just wanted to thank you fellaz for that amazing initiative!

We are definitely going to have a look at that. Are there any plans to sync the releases with the Trivy Releases? .. We are currently evaluating the Trivy Operator 0.7.1

**Comment by fjogeleit** [comment]
Hey, thanks for your feedback. Yes - as soon as I find some time I will upgrade the dependencies and mappings

**Comment by sherifkayad** [comment]
Great to know. Thanks 😊
