### ISSUE TITLE
ComplianceReports cause a crash

### ISSUE THREAD

**Issue by sherifkayad** [fjogeleit/trivy-operator-polr-adapter#57]
Hi @fjogeleit using the operator / chart v0.2.0, I get the error below despite using the latest Trivy version (then the Pod kinda keeps restarting indefinitely):

```
[INFO] VulnerabilityReports enabled
[INFO] ComplianceReports enabled
[INFO] RbacAssessmentReports enabled
[INFO] ExposedSecretReports enabled
Error: failed to wait for compliance caches to sync: timed out waiting for cache to be synced
Usage:
  trivy-operator-polr-adapter run [flags]

Flags:
  -c, --config string            target configuration file
      --enable-compliance        Enable the transformation of ClusterComplianceDetailReport into ClusterPolicyReports
      --enable-config-audit      Enable the transformation of ConfigAuditReports into PolicyReports
      --enable-exposed-secrets   Enable the transformation of ExposedSecretReport into PolicyReports
      --enable-kube-bench        Enable the transformation of CISKubeBenchReports into ClusterPolicyReports
      --enable-rbac-assessment   Enable the transformation of RbacAssessmentReport into PolicyReports
      --enable-vulnerability     Enable the transformation of VulnerabilityReports into PolicyReports
  -h, --help                     help for run
  -k, --kubeconfig string        absolute path to the kubeconfig file

failed to wait for compliance caches to sync: timed out waiting for cache to be synced
```

Could that be something that you fixed in v0.2.1? .. also that chart version doesn't seem to be published 😢

**Comment by fjogeleit** [comment]
Could you check if you really have the`ClusterComplianceDetailReport` CRD installed? Otherwise disable this report should help I think this CRD was not supported by the the Trivy Operator. I will check why the latest chart version was not published correctly.

**Comment by sherifkayad** [comment]
@fjogeleit I double checked now .. I only have the `ClusterComplianceReport` CRD from Trivy ..

**Comment by sherifkayad** [comment]
check here for the list of Trivy CRDs => https://aquasecurity.github.io/trivy-operator/v0.9.1/docs/crds/clustercompliance-report/

**Comment by fjogeleit** [comment]
I will have a look on it

**Comment by fjogeleit** [comment]
Support for the ClusterComplianceReport - the `reportType` has to be `all` (detailed) to work.

<img width="1436" alt="Bildschirmfoto 2022-12-17 um 13 24 25" src="https://user-images.githubusercontent.com/16627596/208241706-6b6421eb-f0e5-4d66-84d7-6b51f8010341.png">

**Comment by sherifkayad** [comment]
I will definitely give it a spin very soon. I am busy these days with a couple of workshops with my team then will take some time off till the end of the year. However,  will post my feedback as soon as I can.

In case that didn't come before the end of the year, I wish you a merry Xmas and a happy new year, @fjogeleit !

**Comment by fjogeleit** [comment]
Thanks a lot, you and your team also a great time.

**Comment by sherifkayad** [comment]
@fjogeleit happy new year and sorry for the late feedback .. works like a charm with the newest version of the Helm Chart. Thanks a lot 😄

**Comment by fjogeleit** [comment]
Hey, great to hear, happy new year and thanks for your feedback and requested improvements
