### ISSUE TITLE
Kube API limit

### ISSUE THREAD

**Issue by yuriydzobak** [fjogeleit/trivy-operator-polr-adapter#65]
Hi,
Could you add a functionality to configure RPS to kube-api?
```
I1228 13:41:01.589679       1 request.go:682] Waited for 1.000340418s due to client-side throttling, not priority and fairness, request: PUT:https://10.11.0.1:443/apis/wgpolicyk8s.io/v1alpha2/namespaces/monitoring/policyreports/trivy-audit-polr-replicaset-trivy-operator-adapter-5b849f8bc6
```
It would be nice if this options or improve request to kube api

**Comment by fjogeleit** [comment]
Hey, thanks for your request I will have a look on it.

**Comment by yuriydzobak** [comment]
k8s version: `Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8+k3s1", GitCommit:"648004e4faeaf9e8705386342e95ec9bd211c2b8", GitTreeState:"clean", BuildDate:"2022-11-18T18:29:47Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by yuriydzobak** [comment]
When i disable CSI bench `[INFO] CISKubeBenchReports enabled` I don't see the issue anymore
```
klf trivy-operator-adapter-5b849f8bc6-vmzxz                                                                                                                               
[INFO] VulnerabilityReports enabled

```
Seems, it makes overloading to kube-api

**Comment by fjogeleit** [comment]
Okay, as mentioned in the other issue I will work on documentation and cli output to improve the usability
