### ISSUE TITLE
RBAC permission issue

### ISSUE THREAD

**Issue by yuriydzobak** [fjogeleit/trivy-operator-polr-adapter#66]
The new version is supporting the `InfraAssessmentReport` but rbac doesn't have permission to list resource
https://github.com/fjogeleit/trivy-operator-polr-adapter/blob/3347d0df8bc41c94bafbd7f2f822d498fafaf17d/charts/trivy-operator-polr-adapter/templates/clusterrole.yaml#L10-L23
Could you add `infraassessmentreports` in the list
```
NAME                                                               SHORTNAMES                         APIVERSION                                NAMESPACED   KIND
infraassessmentreports                                             infraassessment,infraassessments   aquasecurity.github.io/v1alpha1           true         InfraAssessmentReport
```
Thanks

**Comment by fjogeleit** [comment]
thanks for reporting, fixed the issue with Helm Chart v0.3.2
