### ISSUE TITLE
Doc: matrix compatibility 

### ISSUE THREAD

**Issue by yuriydzobak** [fjogeleit/trivy-operator-polr-adapter#67]
Hi,
It would be nice if readme has a table with supported version of trivy-operator and which kyverno or CRD version must be.
It helps to upgrade components in right way and answer stupid questions :) 
For example, if trivy-operator published new api version the trivy-adapter would not work anymore

**Comment by fjogeleit** [comment]
Hey, yes - makes definitely sense. I will have a look as soon as I find some time for it.

**Comment by fjogeleit** [comment]
Addressed in #82

**Comment by fjogeleit** [comment]
Added with the 0.4.0 release: https://github.com/fjogeleit/trivy-operator-polr-adapter#support-matrix
